<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>The “Qualitativo” questions | QualMiner: Text mining for the Venezuelan Humanitarian Response in Ecuador</title>
  <meta name="description" content="Exploring qualitative indicators via text mining methods" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="The “Qualitativo” questions | QualMiner: Text mining for the Venezuelan Humanitarian Response in Ecuador" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Exploring qualitative indicators via text mining methods" />
  <meta name="github-repo" content="bedatadriven/QualMiner" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="The “Qualitativo” questions | QualMiner: Text mining for the Venezuelan Humanitarian Response in Ecuador" />
  
  <meta name="twitter:description" content="Exploring qualitative indicators via text mining methods" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="most-effective-question-descriptions.html"/>
<link rel="next" href="textual-data-preparation.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/wordcloud2-0.0.1/wordcloud.css" rel="stylesheet" />
<script src="libs/wordcloud2-0.0.1/wordcloud2-all.js"></script>
<script src="libs/wordcloud2-0.0.1/hover.js"></script>
<script src="libs/wordcloud2-binding-0.2.2/wordcloud2.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">QualMiner</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="part"><span><b>I About data</b></span></li>
<li class="chapter" data-level="" data-path="data-in-activityinfo-over-time.html"><a href="data-in-activityinfo-over-time.html"><i class="fa fa-check"></i>Data in ActivityInfo over time</a></li>
<li class="chapter" data-level="" data-path="data-preparation.html"><a href="data-preparation.html"><i class="fa fa-check"></i>Data preparation</a></li>
<li class="chapter" data-level="" data-path="technical-aspects-of-the-data.html"><a href="technical-aspects-of-the-data.html"><i class="fa fa-check"></i>Technical aspects of the data</a></li>
<li class="part"><span><b>II Descriptive statistics</b></span></li>
<li class="chapter" data-level="" data-path="recode-table.html"><a href="recode-table.html"><i class="fa fa-check"></i>Recode table</a></li>
<li class="chapter" data-level="" data-path="partners.html"><a href="partners.html"><i class="fa fa-check"></i>Partners</a></li>
<li class="chapter" data-level="" data-path="partners-entering-narrative-data.html"><a href="partners-entering-narrative-data.html"><i class="fa fa-check"></i>Partners entering narrative data</a></li>
<li class="chapter" data-level="" data-path="which-partners-do-enter-more-records-with-narrative-data-per-months.html"><a href="which-partners-do-enter-more-records-with-narrative-data-per-months.html"><i class="fa fa-check"></i>Which partners do enter more records with narrative data per months?</a></li>
<li class="chapter" data-level="" data-path="direct-and-indirect-fields.html"><a href="direct-and-indirect-fields.html"><i class="fa fa-check"></i>Direct and indirect fields</a></li>
<li class="chapter" data-level="" data-path="the-number-of-narrative-records-in-sectors.html"><a href="the-number-of-narrative-records-in-sectors.html"><i class="fa fa-check"></i>The number of narrative records in sectors</a></li>
<li class="chapter" data-level="" data-path="cantons-and-provinces-entering-narrative-data.html"><a href="cantons-and-provinces-entering-narrative-data.html"><i class="fa fa-check"></i>Cantons and provinces entering narrative data</a></li>
<li class="chapter" data-level="" data-path="how-many-individuals-are-entering-data.html"><a href="how-many-individuals-are-entering-data.html"><i class="fa fa-check"></i>How many individuals are entering data?</a></li>
<li class="part"><span><b>III Response quality</b></span></li>
<li class="chapter" data-level="" data-path="response-quality.html"><a href="response-quality.html"><i class="fa fa-check"></i>Response quality</a></li>
<li class="chapter" data-level="" data-path="variance-of-response-word-count-per-sector.html"><a href="variance-of-response-word-count-per-sector.html"><i class="fa fa-check"></i>Variance of response word count per sector</a></li>
<li class="chapter" data-level="" data-path="average-word-count-per-sector.html"><a href="average-word-count-per-sector.html"><i class="fa fa-check"></i>How much does the average word count differ between sectors?</a></li>
<li class="chapter" data-level="" data-path="distribution-of-word-counts-in-response-fields.html"><a href="distribution-of-word-counts-in-response-fields.html"><i class="fa fa-check"></i>Distribution of word counts in response fields</a></li>
<li class="chapter" data-level="" data-path="which-sectors-do-receive-high-word-counts-in-responses.html"><a href="which-sectors-do-receive-high-word-counts-in-responses.html"><i class="fa fa-check"></i>Which sectors do receive high word counts in responses?</a></li>
<li class="chapter" data-level="" data-path="median-word-count-of-responses.html"><a href="median-word-count-of-responses.html"><i class="fa fa-check"></i>Median word count of responses</a></li>
<li class="chapter" data-level="" data-path="the-description-field.html"><a href="the-description-field.html"><i class="fa fa-check"></i>The Description field</a></li>
<li class="chapter" data-level="" data-path="most-effective-question-descriptions.html"><a href="most-effective-question-descriptions.html"><i class="fa fa-check"></i>Most effective question &amp; descriptions</a></li>
<li class="chapter" data-level="" data-path="the-qualitativo-questions.html"><a href="the-qualitativo-questions.html"><i class="fa fa-check"></i>The “Qualitativo” questions</a></li>
<li class="part"><span><b>IV Text mining</b></span></li>
<li class="chapter" data-level="" data-path="textual-data-preparation.html"><a href="textual-data-preparation.html"><i class="fa fa-check"></i>Textual data preparation</a></li>
<li class="chapter" data-level="" data-path="most-common-words.html"><a href="most-common-words.html"><i class="fa fa-check"></i>Most common words</a></li>
<li class="chapter" data-level="" data-path="the-key-themes-by-tf-and-tf-idf.html"><a href="the-key-themes-by-tf-and-tf-idf.html"><i class="fa fa-check"></i>The key themes by tf and tf-idf</a></li>
<li class="chapter" data-level="" data-path="how-does-the-term-frequency-change-over-time-in-sectors.html"><a href="how-does-the-term-frequency-change-over-time-in-sectors.html"><i class="fa fa-check"></i>How does the term frequency change over time in sectors?</a></li>
<li class="chapter" data-level="" data-path="n-grams.html"><a href="n-grams.html"><i class="fa fa-check"></i>n-grams</a></li>
<li class="chapter" data-level="" data-path="most-used-bigrams.html"><a href="most-used-bigrams.html"><i class="fa fa-check"></i>Most used bigrams</a></li>
<li class="chapter" data-level="" data-path="word-co-occurrences-and-correlations.html"><a href="word-co-occurrences-and-correlations.html"><i class="fa fa-check"></i>Word co-occurrences and correlations</a></li>
<li class="chapter" data-level="" data-path="part-of-speech-tagging.html"><a href="part-of-speech-tagging.html"><i class="fa fa-check"></i>Part of speech tagging</a></li>
<li class="chapter" data-level="" data-path="dates-and-years-in-the-responses.html"><a href="dates-and-years-in-the-responses.html"><i class="fa fa-check"></i>Dates and years in the responses</a></li>
<li class="chapter" data-level="" data-path="sentiment-analysis.html"><a href="sentiment-analysis.html"><i class="fa fa-check"></i>Sentiment analysis</a></li>
<li class="chapter" data-level="" data-path="wordcloud-responses.html"><a href="wordcloud-responses.html"><i class="fa fa-check"></i>Wordcloud responses</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org/" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">QualMiner: Text mining for the Venezuelan Humanitarian Response in Ecuador</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-qualitativo-questions" class="section level1 unnumbered">
<h1>The “Qualitativo” questions</h1>
<div id="do-the-responses-have-a-question-consisted-of-the-word-qualitativo-lead-to-lesser-word-counts-than-the-others" class="section level4 unnumbered">
<h4>Do the responses have a question consisted of the word “qualitativo” lead to lesser word counts than the others?</h4>
<p>Every response field in <em>ActivityInfo</em> forms has a question field. Particularly,
in the Ecuador monitoring database, some responses have question field, which is
only filled as one-word length “qualitative” or similar variants, and the other
responses have different question fields, which seem to look like that they are
formed as proper questions.</p>
<p>Let’s say that we are interested in that there are any meaningful differences
between the word counts of these responses: one the one hand, the responses
whose question field has “qualitative”, and on the other hand, the remaining
responses.</p>
<p>The variants of “qualitative” term in the question fields are as follows:
‘<em>Act_1_Cualitativo</em>’, ‘<em>Act_2_Cualitativo</em>’, ‘<em>Act_3_Cualitativo</em>’, ‘<em>Act_4_Cualitativo</em>’, ‘<em>Act_5_Cualitativo</em>’, ‘<em>Act_7_Cualitativo</em>’, ‘<em>cualitativo</em>’, ‘<em>Cualitativo</em>’ and ‘<em>Qualitative</em>’</p>
<p>For this kind of analysis, we look at specific sectors such as <strong>VBG</strong>,
<strong>Poblacion</strong> and <strong>Tecnico</strong> because of a couple of reasons. First, they have
higher and similar sample sizes compared to the other sectors in the database.
Second, their variances are similar. The rationale behind this choice is
explained in the <a href="average-word-count-per-sector.html#average-word-count-per-sector"><strong>section</strong></a>.</p>
<p><img src="qualminer_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p><img src="qualminer_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
</div>
<div id="comparison-of-two-groups-by-their-means" class="section level4 unnumbered">
<h4>Comparison of two groups by their means</h4>
<p>After all, we have two groups (which they can also be called as
<em>random processes</em> due to their distinct characteristics) that are from these
sectors:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Qualitative group</strong>: Responses with which their questions have a
‘qualitative’ or a variant word.</p></li>
<li><p><strong>Non-qualitative group</strong>: Responses with which their questions do not have
any ‘qualitative’ or any variant words.</p></li>
</ol>
<p>To begin with, we try to identify the underlying distribution of these groups:</p>
<p><img src="qualminer_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>In the histograms above, we can clearly see that the distribution in the first
group looks less deviated than the distribution of the second one.</p>
<p>In addition to the histograms, we can generate the <em>Q-Q (quantile-quantile)
plots</em> to assess from a different way whether the grouped data deviates from
normal:</p>
<p><img src="qualminer_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>The first Q-Q plot shows that the deviations from the straight line are high.
This should indicate that the data does not deviate from normal. The
observations in the second plot are more aligned with its line.</p>
<p>Since the assumption of normality is violated in these <em>random processes</em>, we
consider performing <em>bootstrapping</em>, which resamples the data with replacements
so that the observations can be selected more than once,
with <em>1000</em> samples. After that, we can use the bootstrapped data to
calculate the confidence intervals.</p>
<p>After bootstrapping, the distribution of groups looks pretty normal:</p>
<p><img src="qualminer_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>We calculate the <em>bootstrap confidence intervals</em> at the confidence levels of
<em>90</em>, <em>95</em> and <em>99</em> in order to see the difference between the means in response
word count of these groups.</p>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = results, conf = c(0.9, 0.95, 0.99), type = &quot;bca&quot;)
## 
## Intervals : 
## Level       BCa          
## 90%   (-3.091, 10.210 )   
## 95%   (-4.594, 11.434 )   
## 99%   (-8.679, 13.605 )  
## Calculations and Intervals on Original Scale
## Some BCa intervals may be unstable</code></pre>
<p>As a result, based on the resampled data, the difference in mean between those
groups at <em>95%</em> confidence level are
in between <em>-4.59</em> and <em>11.43</em>.
A crude interpretation of this would be that the mean interval does not show too
much significance that the terms in the question fields do not affect the word
count in the response fields. A further either quantiative or qualitative study
is recommended.</p>

</div>
</div>



</div>
            </section>

          </div>
        </div>
      </div>
<a href="most-effective-question-descriptions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="textual-data-preparation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": {}
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"edit": null
},
"search": true
});
});
</script>

</body>

</html>
