
# The key themes by tf and tf-idf {-}

We can look at the key themes in each topic by measuring the
term-frequency and tf-idf[^20].

> tf–idf or TFIDF, short for term frequency–inverse document frequency, is a
numerical statistic that is intended to reflect how important a word is to a
document in a collection or corpus.

```{r, bind_tf_idf}
tf_idf_by_form <- response.tokens %>% 
  group_by(formNameRecode) %>% 
  dplyr::filter(!word_stem %in% c("personar", "mujer", "hombre", "formación", "atención")) %>% 
  count(word_stem) %>% 
  tidytext::bind_tf_idf(word_stem, formNameRecode, n)
```

```{r, fig.width=7, fig.height=7, fig.align='center'}
TOP.N <- 15
response.tokens %>% 
  group_by(Month) %>% 
  count(word_stem) %>% 
  arrange(desc(n)) %>% 
  slice(seq(TOP.N)) %>% 
  ungroup() %>% 
  dplyr::filter(!word_stem %in% c("personar", "mujer", "hombre", "formación", "atención")) %>% 
  mutate(Month = forcats::as_factor(Month),
         Word = tidytext::reorder_within(word_stem, n, Month)) %>% 
  ggplot(aes(Word, n, fill = Month)) +
  geom_col(stat = "identity") +
  coord_flip() +
  facet_wrap(~Month, scales = "free") +
  tidytext::scale_x_reordered() + 
  theme_ecuador1(border = TRUE) +
  theme(legend.position = "none") +
  labs(
    title = paste("The top", TOP.N, "most common words in responses per month"),
    subtitle = "Measured by using 'term frequency'"
  ) +
  xlab(NULL) +
  ylab(NULL)
```

```{r, fig.width=12, fig.height=10, fig.align='center'}
TOP.N <- 10
tf_idf_by_form %>% 
  arrange(desc(n)) %>% 
  slice(seq(TOP.N)) %>% 
  ungroup() %>% 
  mutate(formNameRecode = forcats::as_factor(formNameRecode),
         Word = tidytext::reorder_within(word_stem, tf_idf, formNameRecode)) %>% 
  ggplot(aes(Word, tf_idf, fill = formNameRecode)) +
  geom_col(stat = "identity") +
  coord_flip() +
  facet_wrap(~formNameRecode, scales = "free", ncol = 4) +
  tidytext::scale_x_reordered() + 
  theme_ecuador1(border = TRUE) +
  theme(legend.position = "none") +
  labs(
    title = paste("The top", TOP.N, "most common words in responses per month"),
    subtitle = "Measured by using 'tf-idf'"
  ) +
  xlab(NULL) +
  ylab(NULL)
```

[^20:] <https://en.wikipedia.org/wiki/Tf-idf> Accessed 10 September, 2019.

