
# "Qualitativo" questions {-}

*Does the questions formed by the word "qualitativo" create lesser or longer responses?*

Almost all questions have a form of the term "qualitative" in the question
fields. Here we are interested in the questions that they have nothing but the
term "qualitative".

```{r, include=FALSE}
cual_matches <- local({
  uniq <- unique(narratives.wc$question)
  cual <- "^[C|c]ualitativo$"
  qual <- "^[Q|q]ualitative$"
  act <- "^[A|a]ct_[[:alnum:]]_[C|c]ualitativo$"
  unique(c(
    uniq[grep(cual, uniq)],
    uniq[grep(qual, uniq)],
    uniq[grep(act, uniq)]
  ))
})
```

```{r}
tibble(`"Qualitative questions"` = cual_matches) %>% 
  arrange(.[[1]]) %>% 
  gt() %>% 
  cols_align(
    align = "center"
  )
```

```{r}
qual_narr_wc <- narratives.wc %>% 
  dplyr::filter(question %in% cual_matches)
```

```{r}
qual_narr_wc %>% 
  group_by(formNameRecode) %>% 
  summarise(mean = mean(.responseWordCount))
```

The caveat is that we could not perform a *t-test* here because the data being compared...
